### ISSUE TITLE
Dedup error

### ISSUE THREAD

**Issue by jasonsahl** [dsarov/ARDaP#11]
Derek,

I keep getting a failure at the BAM deduplicate step. The error is:

[1e/e825f9] NOTE: Process `Deduplicate (Bp0036_Bp0036_2002721639_ST9)` terminated with an error exit status (247) -- Error is ignored

The BAM files look ok to me and the gatk command in the nextflow script works when I run separately on those same files. Any thoughts? The Output/bams directory is not being created either.

thanks,

**Comment by dsarov** [comment]
Hi Jason,

Sounds like it's an error passing the data from one stage of the pipeline to the next. This is my first time using next flow so it's highly like I've done something wrong. If the output/ bams isn't created then there's an issue in that step that's stopping the bams from being correctly shuttled along to the next stage.

When was the last time you updated the pipeline? The main branch is a bit further along than the packaged releases so it might be worth grabbing that one and seeing if you hit the same error. If you're running the newest version and you are still hitting the error then I'll see if I can make that part of the code more stable.

Have you used next flow before? It's pretty great but a bit of a learning curve coming from a shell scripting background.

Cheers,

Derek

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonsahl** [comment]
Derek,
The issue with this was the amount of RAM requested. I bumped this up in the config file and it worked. Our system has a hard limit on what is requested.

I am now able to get through most of the pipeline, but it is now failing on the final report:
[f2/4044a5] NOTE: Missing output file(s) `Bp0036_Bp0036_2002721639_ST9.AbR_output.final.txt` expected by process `AbrReport (Bp0036_Bp0036_2002721639_ST9)` -- Error is ignored

It seems like these files are empty: "*AbR_output_snp_indel.txt", although the input files (e.g. annotated.snp.effects.subset) look ok. Any thoughts here? I think this pipeline could be very useful for some work that we have ongoing. I am using the most recent github version.

thanks,
Jason

**Comment by dsarov** [comment]
Hi Jason,

Glad you fixed the issue. I'll update the manual to make sure the queue specifications match the system. Thanks for trying out the software! Super helpful to have someone on a different system to test it out.

I think I might know what the problem is. Are you expecting to find any known determinants in this isolate? I might not have handled the production of the final report for a completely susceptible isolate. If there should be a resistance determinant then could you send me the main next flow log so I can take a look?

Thanks,

Derek

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
